version: 2.1

jobs:
  # ESLint in front-end
  front-end-eslint:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          working_directory: ./front-end
          command: |
            npm install
            npm run lint

  #ESLint in back-end
  back-end-eslint:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          working_directory: ./back-end
          command: |
            npm install
            npm run lint

  #Build and deploy front-end
  front-end-deploy:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: 
          working_directory: ./front-end
          command: |
            npm install
            npm i vercel
            DEPLOYMENT_URL=$(vercel --name $CI_PROJECT_NAME --confirm -t $VERCEL_TOKEN)
            vercel

  #Build and deploy back-end
  back-end-deploy:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: 
          working_directory: ./back-end
          command: |
            npm install
            vercel

workflows:
  Workflow:
    jobs:
      - front-end-eslint
      - back-end-eslint
      # - front-end-deploy:
      #     requires:
      #       - front-end-eslint

  # Back-end-workflow:
  #   jobs:
  #     - front-end-eslint
      # - front-end-deploy:
      #     requires:
      #       - front-end-eslint
  # deploy to test on staging