version: 2.1

jobs:
  front-end-test:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run: 
          working_directory: ./front-end
          name: Run front end
          command: pwd
      - run: pwd
      - run: echo 'hello'

workflows:
  Cd-frontend:
    jobs:
      - front-end-test
      # deploy to test on staging